name: droidconke2020_flutter
description: The official DroidconKE 2020 Conference App made with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stetho: ^0.6.0-dev.1
  dio: ^3.0.9
  freezed_annotation:
  rxdart: ^0.24.1
  provider: ^4.1.2
  shared_preferences: ^0.5.7+3
  google_fonts: ^1.1.0
  flutter_svg: ^0.17.4
  url_launcher: ^5.4.10
  community_material_icon:
  clipboard_manager: ^0.0.4
  flutter_form_builder: ^3.10.1
  cached_network_image: ^2.2.0+1
  debug_mode: ^0.1.1
  firebase_analytics: ^5.0.14
  firebase_crashlytics: ^0.1.3+3
  firebase_performance: ^0.3.2
  google_sign_in: ^4.5.1
  dio_firebase_performance: ^0.1.0
  dio_http_cache: ^0.2.6
  json_serializable: ^3.3.0
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  hydrated_bloc: ^4.0.0
  get_it: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.10.9
  build_runner:
  # flutter packages pub run build_runner watch --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/afrikons/


